version: 0.0

os: linux

files:
  - source: /java-tomcat-sample/target/*.war
   destination: /opt/apache-tomcat-9.0.35/webapps

# hooks:
#   ApplicationStop:
#     - location: stop-process.sh
#       timeout: 180
#       runas: root
#   ApplicationStart:
#     - location: start-process.sh
#       timeout: 180
#       runas: root
