version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase.
      - cd java-tomcat-sample
      - mvn install
      - aws ecr create-repository --repository-name docker-testing --region us-east-1
#       - $(docker tag docker-test ACCOUNT-ID.dkr.ecr.us-east-1.amazonaws.com/docker-testing)
      
  build:
    commands:
      - echo Build started on `date`
      - ls


  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
