version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase.
      - cd java-tomcat-sample
      - mvn install
      - systemctl start docker
      - aws ecr create-repository --repository-name docker-testing --region us-east-1
      - docker tag docker-test 067663653687.dkr.ecr.us-east-1.amazonaws.com/docker-testing
      - aws ecr get-login-password | docker login --username AWS --password-stdin 067663653687.dkr.ecr.us-east-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - cat /etc/group | grep docker
#       - docker push 067663653687.dkr.ecr.us-east-1.amazonaws.com/docker-testing


  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
