AWSTemplateFormatVersion: 2010-09-09
Description: --- deploy stack

Parameters: 
  env:
    Description: dev/qa/prod
    Type: String
  AZ:
    Description: select AZ
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1a
  image: 
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: amazon-linux
  instancetype:
    Description: select instance type
    Type: String
    Default: t2.micro
  keyname:
    Description: select key
    Type: AWS::EC2::KeyPair::KeyName
    Default: awskey2
  SG:
    Description: select SG
    Type: AWS::EC2::SecurityGroup::GroupName
    Default: SG1

Resources: 
  ec2instance:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: !Ref AZ
      ImageId: !Ref image
      InstanceType: !Ref instancetype
      KeyName: !Ref keyname
      SecurityGroups: 
        - !Ref SG
      Tags: 
        - Key: Name
          Value: !Join ["-", [ !Ref env,!Ref AWS::StackName]]
      UserData:
        Fn::Base64:
            !Sub |
              #!/bin/bash
              sudo yum update -y
              sudo yum install ruby -y
              sudo yum install wget -y
              wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
              chmod +x ./install
              sudo ./install auto
              sudo systemctl start codedeploy-agent